# Generated by Django 4.1.5 on 2023-01-19 11:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=100)),
                ("spent_money", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                (
                    "gems",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=50), default=list, size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("quantity", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="processor.client")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="processor.item")),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="transactions",
            field=models.ManyToManyField(related_name="clients", to="processor.transaction"),
        ),
    ]
