# Generated by Django 4.1.5 on 2023-01-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="spent_money",
            field=models.FloatField(default=0),
        ),
    ]
