# pull official base image
FROM python:3.10-slim-bullseye as builder

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1

RUN apt-get update \
    && apt-get install --yes --no-install-recommends gcc g++ libffi-dev libpq-dev python-dev\
    && rm -rf /var/lib/apt/lists/*
# install dependencies
COPY ./api/requirements-dev.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements-dev.txt

# pull official base image
FROM python:3.10-slim-bullseye

# create the appropriate directories
ENV APP_HOME=/var/www/deals/api
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

# install dependencies
COPY --from=builder /usr/src/app/wheels /wheels
COPY --from=builder /usr/src/app/requirements-dev.txt .
RUN apt-get update \
    && apt-get install --yes --no-install-recommends build-essential libpq-dev \
    && pip install --no-cache /wheels/*

# copy project
COPY .. $APP_HOME
